version: '3.4'

services:
    mongodb:
        container_name: mongo.db
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/var/lib/mongodb/data
        restart: always
        networks:
            - erp
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: Tanhoa@123$$
            MONGO_INITDB_DATABASE: admin
    
    sqlserver:
        container_name: sqlserver.db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - '1433:1433'
        volumes:
            - sqlserver-data:/var/lib/sqlserver/data
        networks:
            - erp
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD : Tanhoa123#@!

networks:
    erp:
        driver: bridge
volumes:
    mongo-data:
    sqlserver-data:
        


